# The using GPU ID
cuda_id: 0
# fine-tuning specify the ckpt dir name you want to load the model params.
finetune: False

# the number of max iteration
max_iter: 200000
# the batch size
batch_size: 18

# the mask augmentaiton flag
mask_augment: False

# UNet layer size
layer_size: 7

# loss parameters
valid_coef: 1.0
hole_coef: 6.0
tv_coef: 0.1
perc_coef: 0.05
style_coef: 120.0
# total variation calcuration method (mean or sum)
tv_loss: mean

# Optimization
optim: Adam
initial_lr: 0.0002
finetune_lr: 0.0005
momentum: 0
weight_decay: 0

# visualizing the output images
vis_interval: 1000
# saving the model
save_model_interval: 50000
# printing the losses to standard output line
log_interval: 100

# paths
data_root: ~/data
ckpt: ckpt
